# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b124d83379518258e6a133a5fd350f812afc83d877488236707da0c02975bc83cf99dd50525e01b94659501d224ec42c82b6bf00454b1fcca1d063058c53903b

test:
  secret_key_base: 78b191ee4bd2c154a298107d6ac3ddf0ac46256525c13dc651c0965bc127681de33f489d3f771236b672165a07ee331f69ffa06edf39b5c597bcb3a734d51190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
